'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isRightSidebarVisible, setIsRightSidebarVisible] = useState(true);

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col">
          {/* Header */}
          <header className="bg-gray-800 text-white p-4 shadow-md">
            <div className="container mx-auto flex justify-between items-center">
              <h1 className="text-xl font-bold">Your App Name</h1>
              <button
                onClick={() => setIsRightSidebarVisible(!isRightSidebarVisible)}
                className="bg-blue-600 hover:bg-blue-700 px-3 py-1 rounded text-sm"
              >
                {isRightSidebarVisible ? 'Hide Sidebar' : 'Show Sidebar'}
              </button>
            </div>
          </header>

          {/* Main Content Area with Sidebars */}
          <div className="flex flex-1">
            {/* Left Sidebar */}
            <aside className="w-64 bg-gray-100 border-r border-gray-300 p-4">
              <nav>
                <h2 className="text-lg font-semibold mb-4">Navigation</h2>
                <ul className="space-y-2">
                  <li><a href="#" className="text-blue-600 hover:underline">Home</a></li>
                  <li><a href="#" className="text-blue-600 hover:underline">About</a></li>
                  <li><a href="#" className="text-blue-600 hover:underline">Services</a></li>
                  <li><a href="#" className="text-blue-600 hover:underline">Contact</a></li>
                </ul>
              </nav>
            </aside>

            {/* Main Content */}
            <main className="flex-1 p-6">
              {children}
            </main>

            {/* Right Sidebar */}
            {isRightSidebarVisible && (
              <aside className="w-64 bg-gray-50 border-l border-gray-300 p-4">
                <div>
                  <h2 className="text-lg font-semibold mb-4">Quick Links</h2>
                  <ul className="space-y-2">
                    <li><a href="#" className="text-blue-600 hover:underline">Documentation</a></li>
                    <li><a href="#" className="text-blue-600 hover:underline">Support</a></li>
                    <li><a href="#" className="text-blue-600 hover:underline">FAQ</a></li>
                  </ul>
                </div>
              </aside>
            )}
          </div>

          {/* Footer */}
          <footer className="bg-gray-800 text-white p-4 mt-auto">
            <div className="container mx-auto text-center">
              <p>&copy; 2024 Your App Name. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
