'use client';

import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${poppins.variable} antialiased bg-black/80 backdrop-blur-sm font-sans`}>
        <div className="min-h-screen flex flex-col bg-gray-900/50 backdrop-blur-md">
          <Header />

          <div className="flex flex-1">
            <LeftSidebar />

            <main className="flex-1 p-6 bg-black/20 backdrop-blur-sm">
              {children}
            </main>

            <RightSidebar />
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
